'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FrmConsModifClientes

    '''<summary>
    '''regexIDClienteActualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexIDClienteActualizar As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxIDBusquedactualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxIDBusquedactualizar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnActualizarCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizarCliente As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''regexNombreEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexNombreEdit As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''TxbNombreActualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxbNombreActualizar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexApellidosActualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexApellidosActualizar As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxApellidosActualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxApellidosActualizar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxIdentificacionActualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxIdentificacionActualizar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexTelefeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexTelefeno As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxTelefonoActualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxTelefonoActualizar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexMail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxMailActualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxMailActualizar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxDirExaActualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxDirExaActualizar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexDistrito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexDistrito As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxDistritoActualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxDistritoActualizar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexProv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexProv As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''inputProvinciaEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputProvinciaEdit As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''regexCanton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexCanton As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''inputCantonEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputCantonEdit As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''BtnGuardarCambiosModificarCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGuardarCambiosModificarCliente As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnEliminarCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEliminarCliente As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblAlertaClientesRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertaClientesRegistro As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''vSumaryClientesEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vSumaryClientesEdit As Global.System.Web.UI.WebControls.ValidationSummary
End Class
