'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FrmRegistroClientes

    '''<summary>
    '''regexNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexNombre As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxNombreCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxNombreCliente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexApellidos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexApellidos As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxApellidos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxApellidos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexID As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexTelefeno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexTelefeno As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxTelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxTelefono As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexMail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxMail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxDirExa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxDirExa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexDistrito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexDistrito As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxDistrito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxDistrito As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regexProv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexProv As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''inputProvincia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputProvincia As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''regexCanton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexCanton As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''inputCanton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputCanton As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''btnRegistrarCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegistrarCliente As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblAlertaClientesRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertaClientesRegistro As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''vSumaryClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vSumaryClientes As Global.System.Web.UI.WebControls.ValidationSummary
End Class
