'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmLoginUsuarios

    '''<summary>
    '''regexIDUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regexIDUsuario As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbxIDUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxIDUsuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbxPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btAcceder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btAcceder As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lnkBtAcceder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtAcceder As Global.System.Web.UI.WebControls.LinkButton
End Class
